import Head from "next/head";
import Layout from "../components/Login/layout";
import "bootstrap/dist/css/bootstrap.min.css";
import Button from "react-bootstrap/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>MEBE V.4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="mx-4 my-4 text-3xl font-bold ">Hello Home!</h1>
      </div>
      <Button className="mx-4" variant="primary">
        Dashboard
      </Button>
    </>
  );
}
