import React from "react";
import Head from "next/head";
import Layout from "../components/Login/layout";

export default function Login() {
  return (
    <>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1>Login Page!</h1>
      </Layout>
    </>
  );
}
