import React from "react";
import Head from "next/head";

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="bg-slate-200 text-center text-bold text-blue-500 p-2 ">
        Ini Dashboard Informasi Dit.PA
      </h1>
    </>
  );
}
